### ISSUE TITLE
Can't start the script, errors.

### ISSUE THREAD

**Issue by therawest** [yuma-dev/Autostart-for-Pythonscripts#1]
Hello, I was trying to setup this but I get these errors...how to solve this?
![Screenshot_2](https://user-images.githubusercontent.com/96497111/168477050-db03b06b-0e02-4d6d-b84d-9aad3d79f0eb.png)

**Comment by yuma-dev** [comment]
Did you already pip install pyuac? if yes then try to pip install PyWin32

**Comment by therawest** [comment]
I did install pywin32 but this is not what I thought it is though,.,
Can you maybe help me with adding autorun to my python script?
If you can please hit me up on discord 
#RAw:8033

Its only 32 lines of code in my script and I tried numerous ways to add it to startup and it just doesn't work..

**Comment by yuma-dev** [comment]
The Script works like this :

You dont add it to your Script, it is a standanlone Script
Then you put it in the directory where your personal python script is and run it
